version: '3'
services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - .:/var/www
            - vendor:/var/www/vendor
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        container_name: db
        image: 'bitnami/mysql:latest'
        ports:
            - '${DB_PORT:-3306}:${DB_PORT:-3306}'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        ports:
            - '${PHPMYADMIN_PORT:-8001}:80'
        environment:
            - PMA_HOST=mysql
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    db_data: {}
    vendor: {}
    sail-mysql:
        driver: local
